# Generated by Django 5.0.2 on 2024-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_remove_exam_course_id_exam_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="video_url",
        ),
        migrations.AddField(
            model_name="exam",
            name="video_embed",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
