# Generated by Django 5.0.2 on 2024-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_remove_exam_video_url_exam_video_embed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="audio_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
